### ISSUE TITLE
ArkInventoryClassicCompanion.lua and other stuff

### ISSUE THREAD

**Issue by PeTeFIN** [arkayenro/arkinventory-classic#1]
- You get "Message: Error loading Interface\AddOns\ArkInventoryClassic\ArkInventoryClassicCompanion.lua" on every login/UI reload.
- Additionally it says English (US) translations - attempt 1 to 5 and failed: WOW_SKILL_HERBALISM and WOW_SKILL_MINING.
- Restack and Change char dont have a icon, just a green box. 
- Rules button gives out a error, failed to load arkinventory rules: missing.

On the atm current release of addon and Closed beta client.

**Comment by arkayenro** [comment]
companion file error will be fixed next release

translations is expected at the moment, need to find another way to get those words

icons expected, the client wont dump the interface art so i cant tell what the texture filenames are to replace them with

rules button will be fixed next release

i dont have access to the beta so cant test these, only the stress test which is now ended

**Comment by PeTeFIN** [comment]
I'm in closed beta, so cat test any changes for the next 2 days still if
you have time to work on the project.

to 15. elok. 2019 klo 1.50 arkayenro <notifications@github.com> kirjoitti:

**Comment by arkayenro** [comment]
r4-alpha has the changes

**Comment by Mantrain** [comment]
Only r3 seems to be available on curseforge.

**Comment by arkayenro** [comment]
https://www.curseforge.com/wow/addons/ark-inventory-classic/files/2762098

**Comment by PeTeFIN** [comment]
Ok, error popup is fixed, the translation part is still there (guessing needs bit of category cleanup or matching them to classic version of the mining/herb part, did test to pick those professions up, same result), the "coming in next release" minor stuff is obviously still there). 

Only another thing i noticed that on the config mode, if you have the window near the bottom of screen, the rightmouse button menu still opens downwards (and thus partially or almost completely is unusable). Dont know if that can even be controlled in anyway, just mentioning since i noticed it.

But thats more of esthetics thing since you can easily work around it when doing config.

**Comment by arkayenro** [comment]
yeah, i have to find the classic versions of the herb and mining spells to use, which probably wont happen until release

the config is all ace-config based so unfortunately i cant change how it operates

**Comment by arkayenro** [comment]
if possible could you run the following commands and let me know if they are the right spells, the first [1] value is what i would use

/dump GetSpellInfo( 13614 )
/dump GetSpellInfo( 2575 )

first one should be herbalism, the second should be mining

**Comment by PeTeFIN** [comment]
Seems you are correct, these are the replies

for 13614
[1]=”Herbalism”
[3]=136235
[4]=0
[5]=0
[6]=0

And for 2575
[1]=”Mining”,
[3]=136248,
[4]=3200,
[5]=0,
[6]=5


Lähettäjä: arkayenro
Lähetetty: perjantai 16. elokuuta 2019 15.45
Vastaanottaja: arkayenro/arkinventory-classic
Kopio: PeTeFIN; Author
Aihe: Re: [arkayenro/arkinventory-classic] ArkInventoryClassicCompanion.luaand other stuff (#1)

if possible could you run the following commands and let me know if they are the right spells, the first [1] value is what i would use
/dump GetSpellInfo( 13614 )
/dump GetSpellInfo( 2575 )
first one should be herbalism, the second should be mining

**Comment by arkayenro** [comment]
thanks, i'll update the code to use those instead

**Comment by arkayenro** [comment]
icons and translations should be fixed in the next alpha/release
