### ISSUE TITLE
Items incorrectly placed (changes itself over time)

### ISSUE THREAD

**Issue by jhranac** [arkayenro/arkinventory-classic#11]
At first everything works - created some bars, assigned categories to them. All is fine. 
After a while items start creeping into the default bar (first one) without any configuration changes on my end. This changes during one session. Sometimes it fixes itself and then breaks again. 

Attached are two screenshots of the same inventory after login and a couple of hours in-game:

![Annotation 2019-09-01 175346](https://user-images.githubusercontent.com/5394031/64078985-e39dfa80-cce1-11e9-99ff-401f9b149bb6.png)
Please note that even here some of the items are incorrectly placed in the main bar - notably the tradeskill materials (all should be at top), quest items, consumables, etc. Some cloths and leathers are even separated into two bars.

![Annotation 2019-09-01 175320](https://user-images.githubusercontent.com/5394031/64078986-e7ca1800-cce1-11e9-9b73-0320e158fa0b.png)
Eventually all ends up in the main bar.

Reloading ui does not help, flushing the ai cache neither. Sometimes it's enough to just wait, sometimes to travel through a loading screen - though neither fixes everything. There is always something (different each time) broken.

Final edit:
It just fixed itself (again) to a desired target, though for how long it will last I dare not hope. All I did was stand still in thunderbluff:
![Annotation 2019-09-01 180405](https://user-images.githubusercontent.com/5394031/64079077-30ce9c00-cce3-11e9-8a14-5b16a1352eae.png)

**Comment by arkayenro** [comment]
when it happens go into edit mode and check the debug for one of the items in the wrong place

what category is it getting assigned?

**Comment by jhranac** [comment]
Version 1.00.04

I've compared those two items - which should be placed in the same bar:
![two items](https://user-images.githubusercontent.com/5394031/64091536-e4ba4080-cd50-11e9-899a-46d5ae0d8283.png)

Bar 8 (correct bar) settings:
![bar settings](https://user-images.githubusercontent.com/5394031/64091559-fef41e80-cd50-11e9-8937-e758e2855272.png)

Correctly placed leather debug:
![correct leather](https://user-images.githubusercontent.com/5394031/64091576-0b787700-cd51-11e9-8905-f3570f719eb1.png)

Incorrectly placed leather:
![bad leather](https://user-images.githubusercontent.com/5394031/64091582-1501df00-cd51-11e9-926d-e5c6986bb669.png)

**Comment by jhranac** [comment]
After a bit of gameplay the placement is broken in a different way. Now the same item (different stack, same item type) is in two groups. I've tried to assign it to the proper category manually. Did not help at all, there was no change after that.

All leathers should be together at the very least, but they end up separated. the 2x 20 stacks correctly in bar 9, the incomplete stacks in bar 1 - incorrectly:
![two items](https://user-images.githubusercontent.com/5394031/64100484-f6f5a800-cd6b-11e9-841a-467a6595d796.png)


Correctly placed leather:
![correct leather](https://user-images.githubusercontent.com/5394031/64100495-fd841f80-cd6b-11e9-9af2-f33f38cdeb46.png)


Incorrectly placed leather:
![bad leather](https://user-images.githubusercontent.com/5394031/64100508-037a0080-cd6c-11e9-99e7-76c06dfec94d.png)

**Comment by arkayenro** [comment]
have you got the new item category enabled?  thats really the only thing that would explain why the same item is in two different locations.

config > settings > designs > the design you are using > items > style > new items

**Comment by jhranac** [comment]
*facepalm* You dear sir are a god. Thanks. 

New items was enabled. Disabling that moves all items to appropriate place. If that breaks again I'll let you know, but right now all looks good. Even the bank now shows proper grouping! 

Sorry for the time wasted and thanks for educating me in the ways of arkInventory.
