### ISSUE TITLE
Quiver...

### ISSUE THREAD

**Issue by Svarten** [arkayenro/arkinventory-classic#2]
ArkInventory does not seem to like quivers when equiped in a bag slot :)

**Comment by arkayenro** [comment]
i'll create a hunter and see if i can work out what the issue is

**Comment by arkayenro** [comment]
ive got arrows working, not sure if bullets are different, will need to level up a bit to see if bullets will go into an arrow quiver or not, if not then i need to setup "quivers" for bullets as well

**Comment by arkayenro** [comment]
should be fixed in 1.0.4 but probably needs more work

**Comment by Svarten** [comment]
My thanks, the warning spam in chat was annoying as hell, I love ArkInventory though so... :)
