### ISSUE TITLE
Failed To Load ArkInventoryClassicConfig: Missing

### ISSUE THREAD

**Issue by Amadeus-** [arkayenro/arkinventory-classic#3]
Currently unable to use configuration or rules with the error message "Failed to Load ArkInventoryClassicConfig: Missing" or "Failed to Load ArkInventoryClassicRules: Missing".   There are no LUA errors, but nothing happens but that error message.

I'm on the latest version as of the time of this posting:  1.00.03.

Thanks!

**Comment by markisherwood** [comment]
Managed to resolve this issue by moving by copying the four folders in the Modules directory to the Addons directory. Then they appeared as extra addons for me to enable.

**Comment by arkayenro** [comment]
thanks for that.  worked out i setup the curse/twitch packager commands incorrectly.

should be fixed in 1.00.04
