### ISSUE TITLE
Conflict with currency module from addon BrokerAnything

### ISSUE THREAD

**Issue by voyvoy** [arkayenro/arkinventory-classic#8]
Hello, 

there seems to be a conflict with the addon BrokerAnything, specifically with the currency display. The moment I activate Broker to be used by Titan Bar, I get the following error:

Error occured in: Global
Count: 1
Message: ...toryClassic\Externals\Ace3\AceEvent\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "CURRENCY_DISPLAY_UPDATE"
Debug:
   [C]: RegisterEvent()
   ...toryClassic\Externals\Ace3\AceEvent\AceEvent-3.0.lua:33: OnUsed()
   ...Classic\Libs\CallBackHandler\CallbackHandler-1.0.lua:168: RegisterEvent()
   BrokerAnything\modules\Currency.lua:40:
      BrokerAnything\modules\Currency.lua:27
   [C]: ?
   ...toryClassic\Externals\Ace3\AceAddon\AceAddon-3.0.lua:70:
      ...toryClassic\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65
   ...toryClassic\Externals\Ace3\AceAddon\AceAddon-3.0.lua:527: EnableAddon()
   ...toryClassic\Externals\Ace3\AceAddon\AceAddon-3.0.lua:540: EnableAddon()
   ...toryClassic\Externals\Ace3\AceAddon\AceAddon-3.0.lua:620:
      ...toryClassic\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns: [...]  BrokerAnything, vv1.9
 
Not sure, if you are the right person to address this issue or if it's an error on the Broker code.

Regards

**Comment by arkayenro** [comment]
that event doesnt exist in classic so the author of that mod needs to update it

disable AI and test to confirm the error is still there (it should be its just using the shared library in AI)
